### ISSUE TITLE
关于豆瓣音乐的一些问题

### ISSUE THREAD

**Issue by s823023356** [XVXVXXX/DoubanFM#2]
你好，我在使用你的Demo时有几个问题想请教一下。为什么在真机上不能后台播放，而且你之前介绍的锁屏界面的显示是怎么做的？

**Comment by foox07** [comment]
请问播放器是您自己封装的吗?

**Comment by XVXVXXX** [comment]
不是的，播放器是MPMoviePlayer 是 iOS系统自带的

**Comment by foox07** [comment]
请问 MPMoviePlayer 有更详细的音频控制手段吗, 比如用Slider控制音频播放的进度

**Comment by XVXVXXX** [comment]
应该是有的 毕竟是系统封装的控件。 不过我没有去深入研究这个控件的API了。这是我第一个iOS的代码，2年前的东西了，很多都已经不记得了：）
